/*
Copyright 2021 Alejandro Cosin

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// GLOBAL INCLUDES

// PROJECT INCLUDES
#include "../../include/rastertechnique/voxelvisibilityraytracingtechnique.h"
#include "../../include/scene/scene.h"
#include "../../include/core/coremanager.h"
#include "../../include/accelerationstructure/accelerationstructure.h"
#include "../../include/accelerationstructure/accelerationstructuremanager.h"
#include "../../include/material/materialmanager.h"
#include "../../include/material/materialvoxelvisibilityraytracing.h"
#include "../../include/parameter/attributedefines.h"
#include "../../include/parameter/attributedata.h"
#include "../../include/node/node.h"
#include "../../include/texture/texturemanager.h"
#include "../../include/texture/texture.h"
#include "../../include/rastertechnique/staticscenevoxelizationtechnique.h"
#include "../../include/rastertechnique/bufferprefixsumtechnique.h"
#include "../../include/util/vulkanstructinitializer.h"
#include "../../include/util/bufferverificationhelper.h"
#include "../../include/rastertechnique/voxelvisibilityraytracingtechniqueenum.h"

// NAMESPACE
using namespace attributedefines;
using namespace voxelvisibilityraytracingenum;

// DEFINES
const int maxDynamicVoxel = 25000;
// TODO: Unify definition, it is replicated in several places
struct SceneDescription
{
	int objId;
	uint flags;
	mat4 transform;
	mat4 transformIT;
};

// STATIC MEMBER INITIALIZATION

/////////////////////////////////////////////////////////////////////////////////////////////

VoxelVisibilityRayTracingTechnique::VoxelVisibilityRayTracingTechnique(string &&name, string&& className) :
	  RasterTechnique(move(name), move(className))
	, m_materialVoxelVisibilityRayTracing(nullptr)
	, m_staticAccelerationStructure(nullptr)
	, m_accelerationStructure(nullptr)
	, m_rayTracingOffscreen(nullptr)
	, m_voxelVisibility4BytesBuffer(nullptr)
	, m_voxelVisibilityCompactedBuffer(nullptr)
	, m_voxelVisibilityNumberBuffer(nullptr)
	, m_voxelVisibilityDynamicNumberBuffer(nullptr)
	, m_voxelVisibilityFirstIndexBuffer(nullptr)
	, m_voxelVisibilityDebugBuffer(nullptr)
	, m_triangleSampleDataBuffer(nullptr)
	, m_sceneDescriptorStaticBuffer(nullptr)
	, m_sceneDescriptorBuffer(nullptr)
	, m_shaderBindingTableBuffer(nullptr)
	, m_dynamicVoxelBuffer(nullptr)
	, m_dynamicVoxelVisibilityBuffer(nullptr)
	, m_techniquePrefixSum(nullptr)
	, m_shaderBindingTableBuilt(false)
	, m_shaderGroupBaseAlignment(0)
	, m_shaderGroupHandleSize(0)
	, m_shaderGroupSizeAligned(0)
	, m_shaderGroupStride(0)
	, m_numOccupiedVoxel(0)
	, m_prefixSumCompleted(false)
	, m_numElementToProcess(0)
	, m_numRaysPerVoxelFace(0)
	, m_maxDynamicVoxel(maxDynamicVoxel)
{
	m_active              = true;
	m_numRaysPerVoxelFace = 128; // 128 rays that give place to 64 triangles with Delaunay triangulation
}

/////////////////////////////////////////////////////////////////////////////////////////////

VoxelVisibilityRayTracingTechnique::~VoxelVisibilityRayTracingTechnique()
{
	m_active         = false;
	m_needsToRecord  = false;
	m_executeCommand = false;
}

/////////////////////////////////////////////////////////////////////////////////////////////

void VoxelVisibilityRayTracingTechnique::init()
{
	m_voxelVisibility4BytesBuffer = bufferM->buildBuffer(
		move(string("voxelVisibility4BytesBuffer")),
		nullptr,
		256,
		VK_BUFFER_USAGE_STORAGE_BUFFER_BIT  | VK_BUFFER_USAGE_TRANSFER_SRC_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
		VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);

	m_voxelVisibilityDebugBuffer = bufferM->buildBuffer(
		move(string("voxelVisibilityDebugBuffer")),
		nullptr,
		256,
		VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
		VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);

	// TODO: Bake and put in a Uniform Buffer Object (faster than regular buffers)
	vector<float> vectorData;
	prepareTriangleSamplingBuffers(vectorData);

	m_triangleSampleDataBuffer = bufferM->buildBuffer(
		move(string("triangleSampleDataBuffer")),
		vectorData.data(),
		vectorData.size() * sizeof(float),
		VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_SRC_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
		VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);

	// The dynamic voxel buffer where to store all the voxels generated by dynamic scene elements after each execution of
	// the DynamicSceneVoxelizationTechnique technique will have a fixed size to store up to m_maxDynamicVoxel voxels
	m_dynamicVoxelBuffer = bufferM->buildBuffer(
		move(string("dynamicVoxelBuffer")),
		nullptr,
		4 * m_maxDynamicVoxel,
		VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_SRC_BIT | VK_BUFFER_USAGE_VERTEX_BUFFER_BIT,
		VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);

	m_dynamicVoxelVisibilityBuffer = bufferM->buildBuffer(
		move(string("dynamicVoxelVisibilityBuffer")),
		nullptr,
		4 * maxDynamicVoxel * 6 * m_numRaysPerVoxelFace,
		VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_SRC_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
		VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);

	StaticSceneVoxelizationTechnique* sceneVoxelizationTechnique = static_cast<StaticSceneVoxelizationTechnique*>(gpuPipelineM->getRasterTechniqueByName(move(string("StaticSceneVoxelizationTechnique"))));
	
	BBox3D& box = sceneM->refBox();
	
	vec3 max3D;
	vec3 min3D;
	box.getCenteredBoxMinMax(min3D, max3D);
	
	vec3 extent3D = max3D - min3D;
	m_sceneMin    = vec4(min3D.x,    min3D.y,    min3D.z, 0.0f);
	m_sceneExtent = vec4(extent3D.x, extent3D.y, extent3D.z, float(sceneVoxelizationTechnique->getVoxelizedSceneWidth()));

	m_techniquePrefixSum = static_cast<BufferPrefixSumTechnique*>(gpuPipelineM->getRasterTechniqueByName(move(string("BufferPrefixSumTechnique"))));
	m_techniquePrefixSum->refPrefixSumComplete().connect<VoxelVisibilityRayTracingTechnique, &VoxelVisibilityRayTracingTechnique::slotPrefixSumComplete>(this);

	m_rayTracingOffscreen = textureM->buildTexture(move(string("raytracingoffscreen")),
												   VK_FORMAT_R16G16B16A16_SFLOAT,
												   { uint32_t(coreM->getWidth()), uint32_t(coreM->getHeight()), 1 },
												   VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT,
												   VK_IMAGE_ASPECT_COLOR_BIT,
												   VK_IMAGE_ASPECT_COLOR_BIT,
												   VK_IMAGE_LAYOUT_UNDEFINED,
												   VK_IMAGE_LAYOUT_GENERAL,
												   VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT,
												   VK_SAMPLE_COUNT_1_BIT,
												   VK_IMAGE_TILING_OPTIMAL,
												   VK_IMAGE_VIEW_TYPE_2D,
												   0);

	// Use the SceneDescription::flags field to encode the material index
	vectorString vectorTextureResourceName;
	vectorMaterialPtr vectorMaterial = materialM->getElementByClassName(move(string("MaterialIndirectColorTexture")));

	vectorNodePtr vectorNode = sceneM->getByNodeType(eNodeType::E_NT_STATIC_ELEMENT);

	vector<SceneDescription> vectorSceneDescription(vectorNode.size());

	// TODO: Refactor / make method, it is used here twice and in DynamicVoxelVisibilityRayTracingTechnique::init
	forI(vectorNode.size())
	{
		vectorSceneDescription[i].objId       = i;
		vectorMaterialPtr::iterator it        = find(vectorMaterial.begin(), vectorMaterial.end(), vectorNode[i]->getRenderComponent()->getMaterialInstanced());
		assert(it != vectorMaterial.end());

		// Encode in the last 24 bits the index of the material, and in the first bit, a flag to know whether the scene node is
		// static (0) or dynamic (1). The material index refers to an absolute index of all materials. All textures are added to the combined
		// image sampler "textureArrayCombined" in the ray closest hit so preparing acceleration structures with only some scene elements will 
		// not be a problem to sample the correct texture as long as the indices refer to the whole set of materials used in the scene
		uint distance                         = std::distance(vectorMaterial.begin(), it);
		uint isDynamic                        = (vectorNode[i]->getNodeType() == eNodeType::E_NT_STATIC_ELEMENT) ? 0 : 1;
		distance                            <<= 16;
		distance                             |= isDynamic;
		vectorSceneDescription[i].flags       = distance;

		vectorSceneDescription[i].transform   = vectorNode[i]->getModelMat();
		vectorSceneDescription[i].transformIT = glm::inverse(vectorNode[i]->getModelMat());
	}

	m_sceneDescriptorStaticBuffer = bufferM->buildBuffer(move(string("sceneDescriptorStaticBuffer")),
		(void*)vectorSceneDescription.data(),
		sizeof(SceneDescription) * vectorSceneDescription.size(),
		VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT | VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
		VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);

	m_staticAccelerationStructure = accelerationStructureM->buildAccelerationStructure(move(string("staticraytracedaccelerationstructure")), move(vectorNodePtr(vectorNode)));
	
	// Build the acceleration structure with all scene elements (both staic and dynamic)
	vectorNode = sceneM->getByNodeType(eNodeType::E_NT_STATIC_ELEMENT | eNodeType::E_NT_DYNAMIC_ELEMENT | eNodeType::E_NT_SKINNEDMESH_ELEMENT);
	vectorSceneDescription.resize(vectorNode.size());

	forI(vectorNode.size())
	{
		vectorSceneDescription[i].objId       = i;
		vectorMaterialPtr::iterator it        = find(vectorMaterial.begin(), vectorMaterial.end(), vectorNode[i]->getRenderComponent()->getMaterialInstanced());
		assert(it != vectorMaterial.end());

		// Encode in the last 24 bits the index of the material, and in the first bit, a flag to know whether the scene node is
		// static (0) or dynamic (1). The material index refers to an absolute index of all materials. All textures are added to the combined
		// image sampler "textureArrayCombined" in the ray closest hit so preparing acceleration structures with only some scene elements will 
		// not be a problem to sample the correct texture as long as the indices refer to the whole set of materials used in the scene
		uint distance                         = std::distance(vectorMaterial.begin(), it);
		uint isDynamic                        = (vectorNode[i]->getNodeType() == eNodeType::E_NT_STATIC_ELEMENT) ? 0 : 1;
		distance                            <<= 16;
		distance                             |= isDynamic;
		vectorSceneDescription[i].flags       = distance;

		vectorSceneDescription[i].transform   = vectorNode[i]->getModelMat();
		vectorSceneDescription[i].transformIT = glm::inverse(vectorNode[i]->getModelMat());
	}

	m_accelerationStructure = accelerationStructureM->buildAccelerationStructure(move(string("raytracedaccelerationstructure")), move(vectorNodePtr(vectorNode)));

	m_sceneDescriptorBuffer = bufferM->buildBuffer(move(string("sceneDescriptorBuffer")),
		(void*)vectorSceneDescription.data(),
		sizeof(SceneDescription) * vectorSceneDescription.size(),
		VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT | VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
		VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
	
	m_materialVoxelVisibilityRayTracing = static_cast<MaterialVoxelVisibilityRayTracing*>(materialM->buildMaterial(move(string("MaterialVoxelVisibilityRayTracing")), move(string("MaterialVoxelVisibilityRayTracing")), nullptr));
	m_vectorMaterialName.push_back("MaterialVoxelVisibilityRayTracing");
	m_vectorMaterial.push_back(static_cast<Material*>(m_materialVoxelVisibilityRayTracing));

	// The dynamic scene element acceleration structure is built here as it is needed in the pipeline before the DynamicVoxelVisibilityRayTracingTechnique technique
	vectorNodePtr vectorNodeDyamic = sceneM->getByNodeType(eNodeType::E_NT_DYNAMIC_ELEMENT | eNodeType::E_NT_SKINNEDMESH_ELEMENT);
	accelerationStructureM->buildAccelerationStructure(move(string("dynamicraytracedaccelerationstructure")), move(vectorNodePtr(vectorNodeDyamic)));

	m_materialVoxelVisibilityRayTracing->setSceneExtentAndVoxelSize(m_sceneExtent);

	const VkPhysicalDeviceRayTracingPipelinePropertiesKHR& physicalDeviceRayTracingPipelineProperties = coreM->getkPhysicalDeviceRayTracingPipelineProperties();

	m_shaderGroupBaseAlignment = physicalDeviceRayTracingPipelineProperties.shaderGroupBaseAlignment;
	m_shaderGroupHandleSize    = physicalDeviceRayTracingPipelineProperties.shaderGroupHandleSize;
	m_shaderGroupSizeAligned   = uint32_t((m_shaderGroupHandleSize + (m_shaderGroupBaseAlignment - 1)) & ~uint32_t(m_shaderGroupBaseAlignment - 1));
	m_shaderGroupStride        = m_shaderGroupSizeAligned;
}

/////////////////////////////////////////////////////////////////////////////////////////////

void VoxelVisibilityRayTracingTechnique::prepare(float dt)
{
	if (!m_shaderBindingTableBuilt)
	{
		buildShaderBindingTable();
		m_shaderBindingTableBuilt = true;
	}
}

/////////////////////////////////////////////////////////////////////////////////////////////

VkCommandBuffer* VoxelVisibilityRayTracingTechnique::record(int currentImage, uint& commandBufferID, CommandBufferType& commandBufferType)
{
	commandBufferType = CommandBufferType::CBT_GRAPHICS_QUEUE;

	VkCommandBuffer* commandBuffer;
	commandBuffer = addRecordedCommandBuffer(commandBufferID);
	addCommandBufferQueueType(commandBufferID, commandBufferType);
	coreM->allocCommandBuffer(&coreM->getLogicalDevice(), coreM->getGraphicsCommandPool(), commandBuffer);
	coreM->setObjectName(uint64_t(*commandBuffer), VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT, getName());

	coreM->beginCommandBuffer(*commandBuffer);

#ifdef USE_TIMESTAMP
	vkCmdResetQueryPool(*commandBuffer, coreM->getGraphicsQueueQueryPool(), m_queryIndex0, 1);
	vkCmdResetQueryPool(*commandBuffer, coreM->getGraphicsQueueQueryPool(), m_queryIndex1, 1);
	vkCmdWriteTimestamp(*commandBuffer, VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR, coreM->getGraphicsQueueQueryPool(), m_queryIndex0);
#endif
	
	MaterialVoxelVisibilityRayTracing* temp = static_cast<MaterialVoxelVisibilityRayTracing*>(m_vectorMaterial[0]);

	vkCmdBindPipeline(*commandBuffer, VK_PIPELINE_BIND_POINT_RAY_TRACING_KHR, m_materialVoxelVisibilityRayTracing->getPipeline()->getPipeline());

	uint dynamicAllignment  = materialM->getMaterialUBDynamicAllignment();
	uint32_t materialOffset = static_cast<uint32_t>(m_materialVoxelVisibilityRayTracing->getMaterialUniformBufferIndex() * dynamicAllignment);

	uint offsetData[2] = { 0, materialOffset };
	vkCmdBindDescriptorSets(*commandBuffer, VK_PIPELINE_BIND_POINT_RAY_TRACING_KHR, m_materialVoxelVisibilityRayTracing->getPipelineLayout(), 0, 1, &m_materialVoxelVisibilityRayTracing->refDescriptorSet(), 2, &offsetData[0]);

	VkDeviceAddress shaderBindingTableDeviceAddress = m_shaderBindingTableBuffer->getBufferDeviceAddress();
	
	vector<VkStridedDeviceAddressRegionKHR> vectorStridedDeviceAddressRegion(4);
	vectorStridedDeviceAddressRegion[0] = VkStridedDeviceAddressRegionKHR{ shaderBindingTableDeviceAddress + 0u * m_shaderGroupSizeAligned, m_shaderGroupStride, m_shaderGroupSizeAligned * 1 };
	vectorStridedDeviceAddressRegion[1] = VkStridedDeviceAddressRegionKHR{ shaderBindingTableDeviceAddress + 1u * m_shaderGroupSizeAligned, m_shaderGroupStride, m_shaderGroupSizeAligned * 1 };
	vectorStridedDeviceAddressRegion[2] = VkStridedDeviceAddressRegionKHR{ shaderBindingTableDeviceAddress + 2u * m_shaderGroupSizeAligned, m_shaderGroupStride, m_shaderGroupSizeAligned * 1 };
	vectorStridedDeviceAddressRegion[3] = {0, 0, 0};

	vkfpM->vkCmdTraceRaysKHR(*commandBuffer, &vectorStridedDeviceAddressRegion[0], &vectorStridedDeviceAddressRegion[1], &vectorStridedDeviceAddressRegion[2], &vectorStridedDeviceAddressRegion[3], m_numOccupiedVoxel, m_numRaysPerVoxelFace, 6);
	
#ifdef USE_TIMESTAMP
	vkCmdWriteTimestamp(*commandBuffer, VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR, coreM->getGraphicsQueueQueryPool(), m_queryIndex1);
#endif

	coreM->endCommandBuffer(*commandBuffer);

	// NOTE: Clear command buffer if re-recorded
	m_vectorCommand.push_back(commandBuffer);

	return commandBuffer;
}

/////////////////////////////////////////////////////////////////////////////////////////////

void VoxelVisibilityRayTracingTechnique::postCommandSubmit()
{
	m_signalVoxelVisibilityRayTracing.emit();

	m_active         = false;
	m_executeCommand = false;
	m_needsToRecord  = (m_vectorCommand.size() != m_usedCommandBufferNumber);
}

/////////////////////////////////////////////////////////////////////////////////////////////

void VoxelVisibilityRayTracingTechnique::buildShaderBindingTable()
{
	MaterialVoxelVisibilityRayTracing* temp = static_cast<MaterialVoxelVisibilityRayTracing*>(m_vectorMaterial[0]);

	vector<VkRayTracingShaderGroupCreateInfoKHR>& vectorRayTracingShaderGroupCreateInfo = m_materialVoxelVisibilityRayTracing->refShader()->refVectorRayTracingShaderGroupCreateInfo();

	uint numberShaderGroup      = static_cast<uint>(vectorRayTracingShaderGroupCreateInfo.size());
	uint shaderBindingTableSize = numberShaderGroup * m_shaderGroupSizeAligned;

	// Retrieve shader handles
	vector<uint8_t> vectorShaderHandleStorage(shaderBindingTableSize);
	VkResult result = vkfpM->vkGetRayTracingShaderGroupHandlesKHR(coreM->getLogicalDevice(), m_materialVoxelVisibilityRayTracing->getPipeline()->getPipeline(), 0, numberShaderGroup, shaderBindingTableSize, vectorShaderHandleStorage.data());

	assert(result == VK_SUCCESS);

	vector<uint8_t> vectorShaderBindingTableBuffer(shaderBindingTableSize);
	uint8_t* pVectorShaderBindingTableBuffer = static_cast<uint8_t*>(vectorShaderBindingTableBuffer.data());

	forI(numberShaderGroup)
	{
		memcpy(pVectorShaderBindingTableBuffer, vectorShaderHandleStorage.data() + i * m_shaderGroupHandleSize, m_shaderGroupHandleSize);
		pVectorShaderBindingTableBuffer += m_shaderGroupSizeAligned;
	}

	m_shaderBindingTableBuffer = bufferM->buildBuffer(move(string("shaderBindingTable")),
		(void*)vectorShaderBindingTableBuffer.data(),
		sizeof(uint8_t) * vectorShaderBindingTableBuffer.size(),
		VK_BUFFER_USAGE_TRANSFER_SRC_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT | VK_BUFFER_USAGE_SHADER_BINDING_TABLE_BIT_KHR,
		VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
}

/////////////////////////////////////////////////////////////////////////////////////////////

void VoxelVisibilityRayTracingTechnique::slotPrefixSumComplete()
{
	m_numOccupiedVoxel    = m_techniquePrefixSum->getFirstIndexOccupiedElement();
	m_numElementToProcess = m_numOccupiedVoxel * m_numRaysPerVoxelFace * 6; // Each local workgroup will work one side of each voxel in the scene
	m_sceneMin.w          = float(m_numOccupiedVoxel);

	MaterialVoxelVisibilityRayTracing* temp = static_cast<MaterialVoxelVisibilityRayTracing*>(m_vectorMaterial[0]);

	m_materialVoxelVisibilityRayTracing->setSceneMinAndNumberVoxel(m_sceneMin);

	vector<uint> vectorData;
	vectorData.resize(m_numElementToProcess);
	memset(vectorData.data(), maxValue, vectorData.size() * size_t(sizeof(uint)));
	bufferM->resize(m_voxelVisibility4BytesBuffer, vectorData.data(), m_numElementToProcess * sizeof(uint));

	// TODO: Avoid this resize to save memory once debug is done
	bufferM->resize(m_voxelVisibilityDebugBuffer, nullptr, 1450000 * sizeof(uint));

	m_prefixSumCompleted = true;
}

/////////////////////////////////////////////////////////////////////////////////////////////

void VoxelVisibilityRayTracingTechnique::slotVoxelMergeComplete()
{
	if (m_prefixSumCompleted)
	{
		m_vectorCommand.clear();
		m_active = true;
	}
}
/////////////////////////////////////////////////////////////////////////////////////////////

void VoxelVisibilityRayTracingTechnique::prepareTriangleSamplingBuffers(vector<float>& vectorData)
{
	// LOD 2
	// Offset to get triangle number sample for a given triangle number (from 0 to 63): 0
	// Offset to get offset where the barycentric ocordinates of each sample starts: for a given triangle number (from 0 to 63): 64
	// Offset to start reading each sample's barycentric coordinates: 128
	// Total size = 714
	for (int i = 0; i < 6; ++i)
	{
		for (int j = 0; j < 64; ++j)
		{
			vectorData.push_back(arrayTriangleNumberSampleLOD2[i][j]);
		}
	}

	for (int i = 0; i < 6; ++i)
	{
		for (int j = 0; j < 64; ++j)
		{
			vectorData.push_back(arrayTriangleSampleOffsetLOD2[i][j]);
		}
	}

	for (int i = 0; i < 6; ++i)
	{
		for (int j = 0; j < 293; ++j)
		{
			vectorData.push_back(arrayTriangleSampleBarycentricLOD2[j].x);
			vectorData.push_back(arrayTriangleSampleBarycentricLOD2[j].y);
		}
	}

	// LOD 1
	// Offset to get triangle number sample for a given triangle number (from 0 to 63): 714
	// Offset to get offset where the barycentric ocordinates of each sample starts: for a given triangle number (from 0 to 63): 714 + 64 = 778
	// Offset to start reading each sample's barycentric coordinates: 778 + 64 = 842
	// Total size = 714 + 1288 = 2002
	for (int i = 0; i < 6; ++i)
	{
		for (int j = 0; j < 64; ++j)
		{
			vectorData.push_back(arrayTriangleNumberSampleLOD1[i][j]);
		}
	}

	for (int i = 0; i < 6; ++i)
	{
		for (int j = 0; j < 64; ++j)
		{
			vectorData.push_back(arrayTriangleSampleOffsetLOD1[i][j]);
		}
	}

	for (int i = 0; i < 6; ++i)
	{
		for (int j = 0; j < 580; ++j)
		{
			vectorData.push_back(arrayTriangleSampleBarycentricLOD1[j].x);
			vectorData.push_back(arrayTriangleSampleBarycentricLOD1[j].y);
		}
	}

	// LOD 0
	// Offset to get triangle number sample for a given triangle number (from 0 to 63): 2002
	// Offset to get offset where the barycentric ocordinates of each sample starts: for a given triangle number (from 0 to 63): 2002 + 64 = 2066
	// Offset to start reading each sample's barycentric coordinates: 2066 + 64 = 2130
	// Total size = 714 + 1288 + 3994 = 5996
	for (int i = 0; i < 6; ++i)
	{
		for (int j = 0; j < 64; ++j)
		{
			vectorData.push_back(arrayTriangleNumberSampleLOD0[i][j]);
		}
	}

	for (int i = 0; i < 6; ++i)
	{
		for (int j = 0; j < 64; ++j)
		{
			vectorData.push_back(arrayTriangleSampleOffsetLOD0[i][j]);
		}
	}

	for (int i = 0; i < 6; ++i)
	{
		for (int j = 0; j < 1933; ++j)
		{
			vectorData.push_back(arrayTriangleSampleBarycentricLOD0[j].x);
			vectorData.push_back(arrayTriangleSampleBarycentricLOD0[j].y);
		}
	}

	vec2 data0 = arrayTriangleSampleBarycentricLOD0[1524];
	vec2 data1 = arrayTriangleSampleBarycentricLOD0[1525];
	vec2 data2 = arrayTriangleSampleBarycentricLOD0[1526];
	vec2 data3 = arrayTriangleSampleBarycentricLOD0[1527];
	vec2 data4 = arrayTriangleSampleBarycentricLOD0[1528];
	vec2 data5 = arrayTriangleSampleBarycentricLOD0[1529];
	cout << "data0=(" << data0.x << ", " << data0.y << ")" << endl;
	cout << "data1=(" << data1.x << ", " << data1.y << ")" << endl;
	cout << "data2=(" << data2.x << ", " << data2.y << ")" << endl;
	cout << "data3=(" << data3.x << ", " << data3.y << ")" << endl;
	cout << "data4=(" << data4.x << ", " << data4.y << ")" << endl;
	cout << "data5=(" << data5.x << ", " << data5.y << ")" << endl;
	int a = 0;
}

/////////////////////////////////////////////////////////////////////////////////////////////
